[movies.sample]
   stub = 'vort_'
   path = 'movies/test/'
   variable = 'specific z vorticity'
   mode = 'pseudocolor: full state'
   window_x_lo = -3.0
   window_x_hi =  3.0
   make_movie = false
   final_pause = '0f'
   fps = 12
   image_type = 'png'
   movie_type = 'avi'
   xlines = [-0.5, 0.5]

[movies.entr]
   title = "entropy perturbation"
   stub = 'entr_'
   path = 'movies/test'
   variable = 'specific entropy'
   mode = 'pseudocolor: perturbation'
   window_x_lo = -2
   window_x_hi =  2
   window_y_lo = -3
   window_y_hi =  3
   make_movie = false
   final_pause = '0f'
   fps = 12
   image_type = 'png'
   movie_type = 'avi'
   masks = ["buoyant"]
   mask_method = "force low"
   time_lo = 100
   time_hi = 200

[masks.buoyant]
   variable = 'specific entropy'
   mode = 'pseudocolor: perturbation'
   operator = '<='
   threshold = 0

[masks.not_falling]
   variable = 'x velocity'
   operator = "<"
   threshold = 0

[movies.profile1]
   stub = "prof1_"
   path = "movies/test"
   variable = "specific entropy"
   mode = "profile: full state"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"
   xlines = [-0.5, 0.0, 0.5]

[movies.profile2]
   stub = "prof2_"
   path = "movies/test"
   variable = "density"
   mode = "profile: full state"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"

[movies.profile3]
   stub = "prof3_"
   path = "movies/test"
   variable = "specific z vorticity"
   mode = "profile: full state"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"

[movies.profile4]
   stub = "prof4_"
   path = "movies/test"
   variable = "sound speed"
   mode = "profile: full state"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"

[movies.profile5]
   stub = "prof5_"
   path = "movies/test"
   variable = "x velocity"
   mode = "profile: full state"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"

[movies.profile6]
   stub = "prof6_"
   path = "movies/test"
   variable = "pressure"
   mode = "profile: contrast"
   image_type = "png"
   make_movie = false

