[movies.sample]
   stub = 'vort_'
   path = 'movies/test/'
   variable = 'specific z vorticity'
   mode = 'full state'
   window_x_lo = -3.0
   window_x_hi =  3.0
   make_movie = false
   final_pause = '0f'
   fps = 12
   image_type = 'png'
   movie_type = 'avi'

[movies.entr]
   stub = 'entr_'
   path = 'movies/test'
   variable = 'specific entropy'
   mode = 'perturbation'
   make_movie = false
   final_pause = '0f'
   fps = 12
   image_type = 'png'
   movie_type = 'avi'
   masks = ["buoyant"]

[masks.buoyant]
   variable = 'specific entropy'
   mode = 'perturbation'
   operator = '<='
   threshold = 0

[masks.not_falling]
   variable = 'x velocity'
   operator = "<"
   threshold = 0

[movies.profile1]
   stub = "prof1_"
   path = "movies/test"
   variable = "specific entropy"
   mode = "profile"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"

[movies.profile2]
   stub = "prof2_"
   path = "movies/test"
   variable = "density"
   mode = "profile"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"

[movies.profile3]
   stub = "prof3_"
   path = "movies/test"
   variable = "specific z vorticity"
   mode = "profile"
   image_type = "png"
   movie_type = "avi"
   fps = 20
   final_pause = "0.35s"

